const supermarkets = [
  "Loblaws",
  "Sobeys",
  "Metro",
  "Safeway",
  "Save-On-Foods",
  "FreshCo",
  "Giant Tiger",
  "Dollarama",
  "Fortinos",
  "No Frills",
  "Shoppers",
  "Tim Horton",
  "McDonald",
  "Wendy's",
  "Real Canadian Superstore",
  "IGA",
  "Foodland",
  "Thrifty Foods",
  "Farm Boy",
  "Michaels",
  "Walmart",
  "Costco",
  "Whole Foods Market",
  "Kroger",
  "Publix",
  "Albertsons",
  "Aldi",
  "Trader Joe's",
  "Target",
  "Sam's Club",
  "Wegmans",
  "HEB",
  "Meijer",
  "Soriana",
  "Chedraui",
  "Comercial Mexicana",
];

module.exports = supermarkets;
